spring:
  application:
    name: rest-with-spring-boot-and-java
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
logging:
  level:
    root: INFO # root é o log global da aplicação.
    #com.github.aguinaldoNetoDev: TRACE # posso definir um tipo de log para um determinado pacote. Obs: INFO É O DEFAULT